default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= Rails.application.credentials.dig(:database, :pool) || 15 %>

development_default: &development_default
  <<: *default
  host: postgres
  username: postgres
  password: postgres

development:
  primary:
    <<: *development_default
    database: base_project_development
  queue:
    <<: *development_default
    database: base_project_queue_development
    migrations_paths: db/queue_migrate
  cache:
    <<: *development_default
    database: base_project_cache_development
    migrations_paths: db/cache_migrate
  cable:
    <<: *development_default
    database: base_project_cable_development
    migrations_paths: db/cable_migrate

test_default: &test_default
  <<: *default
  host: postgres
  username: postgres
  password: postgres

test:
  primary:
    <<: *test_default
    database: base_project_test_<%= ENV.fetch('TEST_ENV_NUMBER') { 1 } %>
  cache:
    <<: *test_default
    database: base_project_test_cache
    migrations_paths: db/cache_migrate

production_default: &production_default
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

production:
  primary:
    <<: *production_default
    database: <%= Rails.application.credentials.dig(:database, :primary, :name) %>
  cable:
    <<: *production_default
    database: <%= Rails.application.credentials.dig(:database, :cable, :name) %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *production_default
    database: <%= Rails.application.credentials.dig(:database, :queue, :name) %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *production_default
    database: <%= Rails.application.credentials.dig(:database, :cache, :name) %>
    migrations_paths: db/cache_migrate

staging_default: &staging_default
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

staging:
  primary:
    <<: *staging_default
    database: <%= Rails.application.credentials.dig(:database, :primary, :name) %>
  cable:
    <<: *staging_default
    database: <%= Rails.application.credentials.dig(:database, :cable, :name) %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *staging_default
    database: <%= Rails.application.credentials.dig(:database, :queue, :name) %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *staging_default
    database: <%= Rails.application.credentials.dig(:database, :cache, :name) %>
    migrations_paths: db/cache_migrate
