default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 15 } %>

development_default: &development_default
  <<: *default
  host: postgres
  username: postgres
  password: postgres

development:
  primary:
  <<: *development_default
    database: base_project_development
  queue:
    <<: *development_default
    database: base_project_queue_development
    migrations_paths: db/queue_migrate
  cache:
    <<: *development_default
    database: base_project_cache_development
    migrations_paths: db/cache_migrate
  cable:
    <<: *development_default
    database: base_project_cable_development
    migrations_paths: db/cable_migrate

test_default: &test_default
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { ENV["GITHUB_ACTIONS"] ? "localhost" : "postgres" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "postgres" } %>

test:
  primary:
    <<: *test_default
    database: base_project_test_<%= ENV.fetch('TEST_ENV_NUMBER') { 1 } %>
  cache:
    <<: *test_default
    database: base_project_test_cache
    migrations_paths: db/cache_migrate

production_default: &production_default
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  primary:
    <<: *production_default
    database: <%= ENV['POSTGRES_DB_PRIMARY'] %>
  cable:
    <<: *production_default
    database: <%= ENV['POSTGRES_DB_CABLE'] %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *production_default
    database: <%= ENV['POSTGRES_DB_QUEUE'] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *production_default
    database: <%= ENV['POSTGRES_DB_CACHE'] %>
    migrations_paths: db/cache_migrate

staging_default: &staging_default
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

staging:
  primary:
    <<: *staging_default
    database: <%= ENV['POSTGRES_DB_PRIMARY'] %>
  cable:
    <<: *staging_default
    database: <%= ENV['POSTGRES_DB_CABLE'] %>
    migrations_paths: db/cable_migrate
  queue:
    <<: *staging_default
    database: <%= ENV['POSTGRES_DB_QUEUE'] %>
    migrations_paths: db/queue_migrate
  cache:
    <<: *staging_default
    database: <%= ENV['POSTGRES_DB_CACHE'] %>
    migrations_paths: db/cache_migrate
