service: base_project

image: base_project

servers:
  web:
    - <%= ENV['MAIN_HOST'] %>
  jobs:
    hosts:
      - <%= ENV['MAIN_HOST'] %>
    cmd: bundle exec rails solid_queue:start

registry:
  server: localhost:5555

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_ENV: <%= ENV['RAILS_ENV'] %>

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "base_project_storage:/rails/storage"

builder:
  arch: amd64

readiness_delay: 10

proxy:
  app_port: 3000

accessories:
  db:
    image: postgres:17
    host: <%= ENV['DB_HOST'] %>
    port: 5432
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_USER
        - POSTGRES_DB
    directories:
      - postgres:/var/lib/postgresql/data
    cmd: >
      postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=5000 -c pg_stat_statements.track=all

logging:
  driver: journald
